spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education?characterEncoding=utf8&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 12xuhua12.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB



server:
  port: 8700
#  connection-timeout: 18000000





mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

